name: Build and Deploy NGINX Docker Image

on:
  push:
    branches:
      - main  # Change this to your main branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          docker build -t my-custom-nginx-image .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Set your Docker Hub username in Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Set your Docker Hub password in Secrets

      - name: Push Docker Image
        run: |
          docker tag my-custom-nginx-image:latest myusername/my-custom-nginx-image:latest  # Replace with your Docker Hub username
          docker push myusername/my-custom-nginx-image:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        run: |
          ssh user@your-server "docker pull myusername/my-custom-nginx-image:latest && \
                               docker stop my-nginx-container && \
                               docker rm my-nginx-container && \
                               docker run -d -p 80:80 --name my-nginx-container myusername/my-custom-nginx-image:latest"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Add your private SSH key in Secrets
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}  # Add your server's known hosts in Secrets
